"""Public text-to-speech component API."""

from coop_navigation_sds.DialogManagement.speech_pipeline import (
    ChatTTSTextToSpeech,
    F5TextToSpeech,
    KokoroTextToSpeech,
    MeloTextToSpeech,
    PiperTextToSpeech,
    EspeakNgTextToSpeech,
    Qwen3TextToSpeech,
    SpeechEngineSpec,
    SpeechPipelineConfig,
    SpeechPipelineError,
    SpeechSignal,
    TextToSpeechEngine,
    TTS_ENGINE_SPECS,
    WaveFileTextToSpeech,
    WindowsSapiTextToSpeech,
    available_tts_engine_keys,
    platform_default_tts_engine,
    speech_engine_description,
    synthesis_controls,
)

__all__ = [
    "ChatTTSTextToSpeech",
    "F5TextToSpeech",
    "KokoroTextToSpeech",
    "MeloTextToSpeech",
    "PiperTextToSpeech",
    "EspeakNgTextToSpeech",
    "Qwen3TextToSpeech",
    "SpeechEngineSpec",
    "SpeechPipelineConfig",
    "SpeechPipelineError",
    "SpeechSignal",
    "TTS_ENGINE_SPECS",
    "TextToSpeechEngine",
    "WaveFileTextToSpeech",
    "WindowsSapiTextToSpeech",
    "available_tts_engine_keys",
    "platform_default_tts_engine",
    "speech_engine_description",
    "synthesis_controls",
]
