"""Reusable, named synthesis profiles for controlled speech experiments."""

DEFAULT_AGENT_A_AUDIO_PERSONA = "high_clarity_caller"
DEFAULT_AGENT_B_AUDIO_PERSONA = "high_clarity_operator"

COMMON_SYNTHESIS_VALUES = {
    "language": "EN",
    "speed": 1.0,
    "temperature": 0.3,
    "top_p": 0.7,
    "top_k": 20,
    "seed": 11,
    "oral_level": 2,
    "laugh_level": 0,
    "break_level": 4,
    "reference_audio": "",
    "reference_text": "",
    "clarity_level": "clear",
    "hesitation_probability": 0.0,
    "filler_probability": 0.0,
    "stutter_probability": 0.0,
    "clipping_probability": 0.0,
    "station_substitution_probability": 0.0,
    "noise_error_probability": 0.0,
}

SYNTHESIS_FIELDS = (
    "voice",
    "speech_rate",
    "words_per_minute",
    "volume",
    "pitch_semitones",
    "pause_ms",
    "emphasis",
    "clarity_level",
    "hesitation_probability",
    "filler_probability",
    "stutter_probability",
    "clipping_probability",
    "station_substitution_probability",
    "noise_error_probability",
    *COMMON_SYNTHESIS_VALUES,
)

AUDIO_PERSONAS = {
    "high_clarity_caller": {
        "name": "High-clarity caller",
        "description": "Carefully articulated caller voice optimized for reliable speech recognition.",
        "dimensions": ("default", "high_clarity", "caller"),
        "words_per_minute": 140,
        "speech_rate": -3,
        "volume": 100,
        "pitch_semitones": 0,
        "pause_ms": 260,
        "emphasis": "moderate",
        "voice": "",
        "speed": 0.86,
        "temperature": 0.15,
        "top_p": 0.55,
        "top_k": 12,
        "seed": 7,
        "oral_level": 1,
        "break_level": 5,
    },
    "neutral_caller": {
        "name": "Neutral caller",
        "description": "Balanced caller voice with ordinary pace and restrained emphasis.",
        "dimensions": ("baseline", "caller"),
        "words_per_minute": 150,
        "speech_rate": -2,
        "volume": 95,
        "pitch_semitones": 0,
        "pause_ms": 210,
        "emphasis": "none",
        "voice": "",
        "speed": 0.95,
        "temperature": 0.25,
        "seed": 11,
        "break_level": 3,
    },
    "hurried_caller": {
        "name": "Hurried caller",
        "description": "Fast, slightly louder delivery with short punctuation pauses.",
        "dimensions": ("fast", "high_urgency", "caller"),
        "words_per_minute": 245,
        "speech_rate": 7,
        "volume": 100,
        "pitch_semitones": 2,
        "pause_ms": 55,
        "emphasis": "moderate",
        "voice": "",
        "speed": 1.15,
        "temperature": 0.4,
        "seed": 13,
        "oral_level": 5,
        "break_level": 1,
    },
    "hesitant_caller": {
        "name": "Hesitant caller",
        "description": "Slower, quieter delivery with longer pauses and reduced emphasis.",
        "dimensions": ("slow", "hesitant", "caller"),
        "words_per_minute": 135,
        "speech_rate": -2,
        "volume": 82,
        "pitch_semitones": 1,
        "pause_ms": 280,
        "emphasis": "reduced",
        "voice": "",
        "speed": 0.82,
        "temperature": 0.35,
        "seed": 17,
        "oral_level": 5,
        "break_level": 6,
        "clarity_level": "mostly_clear",
        "hesitation_probability": 0.22,
        "filler_probability": 0.12,
    },
    "soft_spoken_caller": {
        "name": "Soft-spoken caller",
        "description": "Low-volume, measured speech useful for recognition robustness tests.",
        "dimensions": ("low_volume", "caller"),
        "words_per_minute": 165,
        "speech_rate": 0,
        "volume": 62,
        "pitch_semitones": -1,
        "pause_ms": 150,
        "emphasis": "reduced",
        "voice": "",
        "speed": 0.9,
        "temperature": 0.2,
        "seed": 19,
        "oral_level": 1,
        "clarity_level": "degraded",
        "clipping_probability": 0.05,
        "noise_error_probability": 0.04,
    },
    "deliberate_caller": {
        "name": "Deliberate caller",
        "description": "Careful articulation with a slow pace and clear phrase boundaries.",
        "dimensions": ("slow", "careful", "caller"),
        "words_per_minute": 145,
        "speech_rate": -1,
        "volume": 92,
        "pitch_semitones": 0,
        "pause_ms": 220,
        "emphasis": "moderate",
        "voice": "",
        "speed": 0.86,
        "temperature": 0.2,
        "seed": 23,
        "oral_level": 1,
        "break_level": 5,
    },
    "clear_operator": {
        "name": "Clear operator",
        "description": "Neutral hotline voice optimized for concise route instructions.",
        "dimensions": ("baseline", "assistant"),
        "words_per_minute": 165,
        "speech_rate": -1,
        "volume": 100,
        "pitch_semitones": 0,
        "pause_ms": 170,
        "emphasis": "none",
        "voice": "",
        "speed": 1.0,
        "temperature": 0.2,
        "seed": 29,
        "oral_level": 1,
        "break_level": 3,
    },
    "high_clarity_operator": {
        "name": "High-clarity operator",
        "description": "Slow, well-separated route instructions optimized for listener comprehension.",
        "dimensions": ("default", "high_clarity", "assistant"),
        "words_per_minute": 145,
        "speech_rate": -3,
        "volume": 100,
        "pitch_semitones": 0,
        "pause_ms": 280,
        "emphasis": "moderate",
        "voice": "",
        "speed": 0.84,
        "temperature": 0.12,
        "top_p": 0.5,
        "top_k": 10,
        "seed": 27,
        "oral_level": 1,
        "break_level": 5,
    },
    "brisk_operator": {
        "name": "Brisk operator",
        "description": "Fast and compact assistant delivery for latency-sensitive conditions.",
        "dimensions": ("fast", "assistant"),
        "words_per_minute": 245,
        "speech_rate": 7,
        "volume": 100,
        "pitch_semitones": 1,
        "pause_ms": 50,
        "emphasis": "moderate",
        "voice": "",
        "speed": 1.12,
        "temperature": 0.3,
        "seed": 31,
        "oral_level": 3,
        "break_level": 1,
    },
    "reassuring_operator": {
        "name": "Reassuring operator",
        "description": "Measured, lower-pitched delivery with stronger phrase emphasis.",
        "dimensions": ("supportive", "assistant"),
        "words_per_minute": 175,
        "speech_rate": 1,
        "volume": 94,
        "pitch_semitones": -2,
        "pause_ms": 150,
        "emphasis": "moderate",
        "voice": "",
        "speed": 0.94,
        "temperature": 0.25,
        "seed": 37,
        "oral_level": 2,
        "break_level": 4,
    },
    "deliberate_operator": {
        "name": "Deliberate operator",
        "description": "Slow, highly segmented instructions for intelligibility experiments.",
        "dimensions": ("slow", "careful", "assistant"),
        "words_per_minute": 150,
        "speech_rate": -1,
        "volume": 98,
        "pitch_semitones": 0,
        "pause_ms": 230,
        "emphasis": "strong",
        "voice": "",
        "speed": 0.84,
        "temperature": 0.18,
        "seed": 41,
        "oral_level": 1,
        "break_level": 6,
    },
    "degraded_caller": {
        "name": "Degraded caller",
        "description": "Understandable but error-prone caller with hesitations, clipped words, and station confusions.",
        "dimensions": ("degraded", "caller"),
        "words_per_minute": 155, "speech_rate": 0, "volume": 70,
        "pitch_semitones": 0, "pause_ms": 330, "emphasis": "reduced", "voice": "",
        "clarity_level": "degraded", "hesitation_probability": 0.18,
        "filler_probability": 0.12, "stutter_probability": 0.08,
        "clipping_probability": 0.08, "station_substitution_probability": 0.08,
        "noise_error_probability": 0.08,
    },
    "barely_understandable_caller": {
        "name": "Barely understandable caller",
        "description": "Severe controlled degradation for repair and failure-localization experiments.",
        "dimensions": ("severe_degradation", "caller"),
        "words_per_minute": 185, "speech_rate": 3, "volume": 48,
        "pitch_semitones": 1, "pause_ms": 420, "emphasis": "reduced", "voice": "",
        "clarity_level": "barely_understandable", "hesitation_probability": 0.28,
        "filler_probability": 0.20, "stutter_probability": 0.16,
        "clipping_probability": 0.18, "station_substitution_probability": 0.16,
        "noise_error_probability": 0.18,
    },
    "degraded_operator": {
        "name": "Degraded operator",
        "description": "Error-prone route delivery used to test caller verification and repair.",
        "dimensions": ("degraded", "assistant"),
        "words_per_minute": 180, "speech_rate": 2, "volume": 68,
        "pitch_semitones": -1, "pause_ms": 280, "emphasis": "reduced", "voice": "",
        "clarity_level": "degraded", "hesitation_probability": 0.10,
        "filler_probability": 0.08, "stutter_probability": 0.06,
        "clipping_probability": 0.08, "station_substitution_probability": 0.10,
        "noise_error_probability": 0.08,
    },
    "barely_understandable_operator": {
        "name": "Barely understandable operator",
        "description": "Severely degraded route delivery intended to trigger clarification and rejection.",
        "dimensions": ("severe_degradation", "assistant"),
        "words_per_minute": 205, "speech_rate": 5, "volume": 45,
        "pitch_semitones": -1, "pause_ms": 360, "emphasis": "reduced", "voice": "",
        "clarity_level": "barely_understandable", "hesitation_probability": 0.16,
        "filler_probability": 0.14, "stutter_probability": 0.14,
        "clipping_probability": 0.20, "station_substitution_probability": 0.18,
        "noise_error_probability": 0.20,
    },
}


def audio_persona_keys(role=None):
    """Return stable profile keys, optionally filtered by intended role."""
    if role is None:
        return tuple(AUDIO_PERSONAS)
    return tuple(
        key
        for key, profile in AUDIO_PERSONAS.items()
        if role in profile.get("dimensions", ())
    )


def get_audio_persona(key, fallback=DEFAULT_AGENT_A_AUDIO_PERSONA):
    """Return a copy of a configured profile."""
    profile = AUDIO_PERSONAS.get(key) or AUDIO_PERSONAS[fallback]
    return {**COMMON_SYNTHESIS_VALUES, **profile}


def synthesis_values(key, fallback=DEFAULT_AGENT_A_AUDIO_PERSONA):
    """Return only fields accepted by the synthesis pipeline."""
    profile = get_audio_persona(key, fallback)
    return {field: profile[field] for field in SYNTHESIS_FIELDS}


def describe_audio_persona(key, fallback=DEFAULT_AGENT_A_AUDIO_PERSONA):
    """Return compact GUI and manifest text for a profile."""
    profile = get_audio_persona(key, fallback)
    dimensions = ", ".join(profile.get("dimensions", ()))
    return (
        f"{profile['description']} Clarity: {profile['clarity_level']}; "
        f"dimensions: {dimensions}."
    )
