"""Controller-layer defaults with environment-variable compatibility."""
import os


def _environment(name, legacy_name, default):
    return os.environ.get(name, os.environ.get(legacy_name, default))


def _environment_bool(name, legacy_name, default):
    return str(_environment(name, legacy_name, default)).lower() in {"1", "true", "on", "yes"}


NUM_TURNS = int(_environment("COOP_NAVIGATION_SDS_NUM_TURNS", "MINILLAMA_NUM_TURNS", "7"))
INVALID_ROUTE_LIMIT = int(_environment("COOP_NAVIGATION_SDS_INVALID_ROUTE_LIMIT", "MINILLAMA_INVALID_ROUTE_LIMIT", "2"))
CONSTRAINT_MISS_LIMIT = int(_environment("COOP_NAVIGATION_SDS_CONSTRAINT_MISS_LIMIT", "MINILLAMA_CONSTRAINT_MISS_LIMIT", "2"))
AGENT_A_TRANSFER_TOLERANCE = int(_environment("COOP_NAVIGATION_SDS_AGENT_A_TRANSFER_TOLERANCE", "MINILLAMA_AGENT_A_TRANSFER_TOLERANCE", "1"))
MAXIMUM_PROGRESSIVE_CONSTRAINTS = int(_environment("COOP_NAVIGATION_SDS_MAXIMUM_PROGRESSIVE_CONSTRAINTS", "MINILLAMA_MAXIMUM_PROGRESSIVE_CONSTRAINTS", "3"))
MINIMUM_COMPARED_ROUTES = int(_environment("COOP_NAVIGATION_SDS_MINIMUM_COMPARED_ROUTES", "MINILLAMA_MINIMUM_COMPARED_ROUTES", "2"))
REQUIRE_CONSTRAINT_RETENTION = _environment_bool("COOP_NAVIGATION_SDS_REQUIRE_CONSTRAINT_RETENTION", "MINILLAMA_REQUIRE_CONSTRAINT_RETENTION", "1")
METRIC_SNAPSHOT_INTERVAL = int(_environment("COOP_NAVIGATION_SDS_METRIC_SNAPSHOT_INTERVAL", "MINILLAMA_METRIC_SNAPSHOT_INTERVAL", "1"))
RESULTS_DIR = _environment("COOP_NAVIGATION_SDS_RESULTS_DIR", "MINILLAMA_RESULTS_DIR", "results")
SESSION_LOG_DIR = _environment("COOP_NAVIGATION_SDS_SESSION_LOG_DIR", "MINILLAMA_SESSION_LOG_DIR", RESULTS_DIR)
SESSION_NAME = "coop_navigation_sds"
DEFAULT_MODEL_PARAM_KEY = "greedy"
SESSION_LOG_PROFILE = _environment("COOP_NAVIGATION_SDS_SESSION_LOG_PROFILE", "MINILLAMA_SESSION_LOG_PROFILE", "runtime").lower()
PROTOCOL_LOG_DIR = _environment("COOP_NAVIGATION_SDS_PROTOCOL_LOG_DIR", "MINILLAMA_PROTOCOL_LOG_DIR", RESULTS_DIR)
