"""Model-layer configuration."""
import os


def _environment(name, legacy_name, default):
    return os.environ.get(name, os.environ.get(legacy_name, default))


MODEL = os.environ.get(
    "COOP_NAVIGATION_SDS_MODEL",
    os.environ.get("MINILLAMA_MODEL", "TinyLlama/TinyLlama-1.1B-Chat-v1.0"),
)
TOKEN = os.environ.get("HF_TOKEN")
DEVICE = os.environ.get(
    "COOP_NAVIGATION_SDS_DEVICE",
    os.environ.get("MINILLAMA_DEVICE", "cpu"),
).lower()
ALLOW_MODEL_DOWNLOAD = os.environ.get(
    "COOP_NAVIGATION_SDS_ALLOW_MODEL_DOWNLOAD",
    os.environ.get("MINILLAMA_ALLOW_MODEL_DOWNLOAD", "0"),
).lower() in {"1", "true", "on", "yes"}

# MODEL_PROVIDER:
# - "transformers": local Hugging Face causal model
# - "openai": OpenAI/ChatGPT-compatible chat completions API
MODEL_PROVIDER = os.environ.get(
    "COOP_NAVIGATION_SDS_MODEL_PROVIDER",
    os.environ.get("MINILLAMA_MODEL_PROVIDER", "transformers"),
).lower()
CHAT_MODEL = os.environ.get("OPENAI_MODEL", "gpt-4o-mini")
CHAT_API_KEY = os.environ.get("OPENAI_API_KEY")
CHAT_BASE_URL = os.environ.get("OPENAI_BASE_URL", "https://api.openai.com/v1")
CHAT_TIMEOUT_SEC = float(
    os.environ.get(
        "COOP_NAVIGATION_SDS_CHAT_TIMEOUT_SEC",
        os.environ.get("MINILLAMA_CHAT_TIMEOUT_SEC", "5"),
    )
)
OLLAMA_MODEL = os.environ.get("OLLAMA_MODEL", "llama3.2:latest")
OLLAMA_BASE_URL = os.environ.get("OLLAMA_BASE_URL", "http://127.0.0.1:11434/api")

MAX_NEW_TOKENS = int(
    os.environ.get(
        "COOP_NAVIGATION_SDS_MAX_NEW_TOKENS",
        os.environ.get("MINILLAMA_MAX_NEW_TOKENS", "96"),
    )
)
GENERATION_MAX_TIME_SEC = float(
    os.environ.get(
        "COOP_NAVIGATION_SDS_GENERATION_MAX_TIME_SEC",
        os.environ.get("MINILLAMA_GENERATION_MAX_TIME_SEC", "5"),
    )
)
MAX_INPUT_TOKENS = int(os.environ.get("COOP_NAVIGATION_SDS_MAX_INPUT_TOKENS", "4096"))

NUM_STATIONS = 36
NUM_LINES = 14
LAYOUT_COLUMNS = None

DEFAULT_HEADWAY_MIN = 5
DEFAULT_TRAVEL_TIME_MIN = 4
MIN_TRAVEL_TIME_MIN = 2
MAX_TRAVEL_TIME_MIN = 6
LINE_TRAVEL_MINUTES_PER_MAP_UNIT = 0.038
MODE_TRAVEL_MINUTES_PER_MAP_UNIT = {
    "metro": 0.025,
    "tram": 0.030,
    "bus": 0.055,
    "walking": 0.060,
}
MODE_HEADWAY_MIN = {
    "metro": 4,
    "tram": 6,
    "bus": 8,
    "walking": 0,
}
MODE_LINE_PREFIXES = {"metro": "M", "tram": "T", "bus": "B"}
MODE_LINE_LIMITS = {"metro": 20, "tram": 25, "bus": 30}
DEFAULT_MAX_WALKING_MIN = 10
LINE_MIN_TRAVEL_TIME_MIN = 2
LINE_MAX_TRAVEL_TIME_MIN = 12
WALKING_MIN_SEGMENT_TIME_MIN = 3
WALKING_MAX_SEGMENT_TIME_MIN = 15
WALKING_BUS_MARGIN_MIN = 1

NETWORK_SEED = 42
LINE_FULLNESS_SEED = 84
MIN_LINE_FULLNESS_PERCENT = 15
MAX_LINE_FULLNESS_PERCENT = 95
STATION_DEMAND_SEED = 126
MIN_STATION_FULLNESS_PERCENT = 8
MAX_STATION_FULLNESS_PERCENT = 98
NEAR_CAPACITY_THRESHOLD_PERCENT = int(_environment("COOP_NAVIGATION_SDS_NEAR_CAPACITY_THRESHOLD_PERCENT", "MINILLAMA_NEAR_CAPACITY_THRESHOLD_PERCENT", "85"))
MORNING_PEAK_CENTER_MIN = 8 * 60 + 15
EVENING_PEAK_CENTER_MIN = 17 * 60 + 30
MIDDAY_PEAK_CENTER_MIN = 12 * 60 + 20
LATE_PEAK_CENTER_MIN = 21 * 60 + 10
PEAK_SPREAD_MIN = 95

FORCE_CONNECTED_NETWORK = True

LINE_COLORS = [
    "#d13f31",
    "#3a8f3a",
    "#4169e1",
    "#f2c230",
    "#9b59b6",
    "#111111",
    "#e67e22",
    "#16a085",
    "#2c3e50",
    "#c0392b",
]
STATION_X_GAP = 120
STATION_Y_GAP = 90
STATION_X_OFFSET = 80
STATION_Y_OFFSET = 70
STATION_ROW_STAGGER = 25
MIN_RING_STATIONS = 4
MIN_LINE_STATIONS = 2
HEADWAY_VARIATION_MOD = 3
LINE_COVERAGE_SCORE_WEIGHT = 10
LINE_KIND_BONUS = 2
LINE_LENGTH_SCORE_DIVISOR = 10
LINE_STOP_OVERRIDES = {}
TRAVEL_TIME_OVERRIDES = {
    ("M1", "Harbor", "Sierra"): 6,
}

TRANSFER_TIME_MIN = 2
MIN_STATION_TRANSFER_TIME_MIN = 1
MAX_STATION_TRANSFER_TIME_MIN = 8
STATION_TRANSFER_SEED = 168
MAX_TRANSFER_MISS_PROBABILITY = float(_environment("COOP_NAVIGATION_SDS_MAX_TRANSFER_MISS_PROBABILITY", "MINILLAMA_MAX_TRANSFER_MISS_PROBABILITY", "0.30"))
MAX_ROUTE_DELAY_PROBABILITY = float(_environment("COOP_NAVIGATION_SDS_MAX_ROUTE_DELAY_PROBABILITY", "MINILLAMA_MAX_ROUTE_DELAY_PROBABILITY", "0.45"))
ACCEPTABLE_DURATION_RATIO = float(_environment("COOP_NAVIGATION_SDS_ACCEPTABLE_DURATION_RATIO", "MINILLAMA_ACCEPTABLE_DURATION_RATIO", "1.5"))
MIN_STAGE_SUBOPTIMAL_OPTIONS = int(_environment("COOP_NAVIGATION_SDS_MIN_STAGE_SUBOPTIMAL_OPTIONS", "MINILLAMA_MIN_STAGE_SUBOPTIMAL_OPTIONS", "1"))
REQUIRE_STAGE_SUBOPTIMAL_OPTIONS = _environment("COOP_NAVIGATION_SDS_REQUIRE_STAGE_SUBOPTIMAL_OPTIONS", "MINILLAMA_REQUIRE_STAGE_SUBOPTIMAL_OPTIONS", "1").lower() in {"1", "true", "on", "yes"}
START_TIME_MIN = 8 * 60 + 7
