"""Model-layer configuration."""
import os

import torch

MODEL = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
TOKEN = os.environ.get("HF_TOKEN")
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# MODEL_PROVIDER:
# - "transformers": local Hugging Face causal model
# - "openai": OpenAI/ChatGPT-compatible chat completions API
MODEL_PROVIDER = os.environ.get("MINILLAMA_MODEL_PROVIDER", "transformers").lower()
CHAT_MODEL = os.environ.get("OPENAI_MODEL", "gpt-4o-mini")
CHAT_API_KEY = os.environ.get("OPENAI_API_KEY")
CHAT_BASE_URL = os.environ.get("OPENAI_BASE_URL", "https://api.openai.com/v1")
CHAT_TIMEOUT_SEC = float(os.environ.get("MINILLAMA_CHAT_TIMEOUT_SEC", "60"))

MAX_NEW_TOKENS = 500
GENERATION_MAX_TIME_SEC = 30
MAX_INPUT_TOKENS = 99999

NUM_STATIONS = 36
NUM_LINES = 10
LAYOUT_COLUMNS = None

DEFAULT_HEADWAY_MIN = 5
DEFAULT_TRAVEL_TIME_MIN = 4
MIN_TRAVEL_TIME_MIN = 2
MAX_TRAVEL_TIME_MIN = 6

NETWORK_SEED = 42
LINE_FULLNESS_SEED = 84
MIN_LINE_FULLNESS_PERCENT = 15
MAX_LINE_FULLNESS_PERCENT = 95
STATION_DEMAND_SEED = 126
MIN_STATION_FULLNESS_PERCENT = 8
MAX_STATION_FULLNESS_PERCENT = 98
MORNING_PEAK_CENTER_MIN = 8 * 60 + 15
EVENING_PEAK_CENTER_MIN = 17 * 60 + 30
MIDDAY_PEAK_CENTER_MIN = 12 * 60 + 20
LATE_PEAK_CENTER_MIN = 21 * 60 + 10
PEAK_SPREAD_MIN = 95

FORCE_CONNECTED_NETWORK = True

LINE_COLORS = [
    "#d13f31",
    "#3a8f3a",
    "#4169e1",
    "#f2c230",
    "#9b59b6",
    "#111111",
    "#e67e22",
    "#16a085",
    "#2c3e50",
    "#c0392b",
]
STATION_X_GAP = 120
STATION_Y_GAP = 90
STATION_X_OFFSET = 80
STATION_Y_OFFSET = 70
STATION_ROW_STAGGER = 25
MIN_RING_STATIONS = 4
MIN_LINE_STATIONS = 2
HEADWAY_VARIATION_MOD = 3
LINE_COVERAGE_SCORE_WEIGHT = 10
LINE_KIND_BONUS = 2
LINE_LENGTH_SCORE_DIVISOR = 10
LINE_STOP_OVERRIDES = {}

TRANSFER_TIME_MIN = 2
START_TIME_MIN = 8 * 60 + 7
