"""Generate exhaustive API and metric reference documentation."""
from __future__ import annotations

import ast
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from coop_navigation_sds.EvaluationMetrics.catalog import (  # noqa: E402
    METRIC_FAMILY_SPECS,
    metric_metadata,
    phase_key,
)


PACKAGE_ROOT = ROOT / "coop_navigation_sds"


def _summary(docstring, fallback):
    text = " ".join(str(docstring or "").strip().split())
    return text.split(". ", 1)[0].rstrip(".") + "." if text else fallback


def _signature(node):
    try:
        return ast.unparse(node.args)
    except Exception:
        return "..."


def generate_api_reference():
    """Write one stable inventory of every Python module, class, function, and method."""
    lines = [
        "# Package API Reference",
        "",
        "Generated by `python scripts/generate_research_docs.py`.",
        "The inventory is produced with Python AST parsing, so generation does not import model, TTS, or ASR providers.",
        "",
    ]
    for path in sorted(PACKAGE_ROOT.rglob("*.py")):
        if "__pycache__" in path.parts:
            continue
        relative = path.relative_to(ROOT).as_posix()
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        module_doc = _summary(ast.get_docstring(tree), "No module-level description is currently defined.")
        lines.extend([f"## `{relative}`", "", module_doc, ""])
        entries = [
            node for node in tree.body
            if isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef))
        ]
        if not entries:
            lines.extend(["No public runtime components are defined in this module.", ""])
            continue
        for node in entries:
            if isinstance(node, ast.ClassDef):
                lines.extend([
                    f"### Class `{node.name}`",
                    "",
                    _summary(ast.get_docstring(node), "Class component; see its typed members and call sites."),
                    "",
                ])
                methods = [
                    child for child in node.body
                    if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef))
                ]
                for method in methods:
                    lines.extend([
                        f"- `{node.name}.{method.name}({_signature(method)})`: "
                        f"{_summary(ast.get_docstring(method), 'Internal class operation.')}",
                    ])
                if methods:
                    lines.append("")
            else:
                lines.extend([
                    f"### Function `{node.name}({_signature(node)})`",
                    "",
                    _summary(ast.get_docstring(node), "Internal module operation."),
                    "",
                ])
    target = ROOT / "API_REFERENCE.md"
    target.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return target


def generate_metric_reference():
    """Write one row per obligatory metric with rationale and evidence contract."""
    lines = [
        "# Metric Reference",
        "",
        "Generated by `python scripts/generate_research_docs.py`.",
        "Every listed metric is obligatory. A metric without sufficient evidence is retained with a null value and an explicit reason.",
        "",
    ]
    for family in METRIC_FAMILY_SPECS:
        phase = phase_key(family)
        lines.extend([
            f"## {family['title']}",
            "",
            family["description"],
            "",
            "| Metric | Meaning | Selection rationale | Required evidence | Calculation | Interpretation |",
            "| --- | --- | --- | --- | --- | --- |",
        ])
        for key, label in family["metrics"]:
            metadata = metric_metadata(key, phase)
            required = ", ".join(metadata.get("required_trace_fields") or ["phase trace"])
            direction = "higher is better" if metadata.get("higher_is_better") else "lower is better"
            bounds = metadata.get("range")
            if bounds:
                interpretation = f"{bounds[0]} to {bounds[1]}; {direction}"
            else:
                interpretation = f"{metadata.get('range_description', metadata.get('unit'))}; {direction}"
            cells = (
                label,
                metadata.get("meaning"),
                metadata.get("selection_rationale"),
                required,
                metadata.get("calculation"),
                interpretation,
            )
            lines.append("| " + " | ".join(str(cell).replace("|", "\\|") for cell in cells) + " |")
        lines.append("")
    target = ROOT / "METRIC_REFERENCE.md"
    target.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return target


def main():
    api_path = generate_api_reference()
    metric_path = generate_metric_reference()
    print(f"Wrote {api_path}")
    print(f"Wrote {metric_path}")


if __name__ == "__main__":
    main()
